=== PabloMartinRavelo/ocs/bundle/edu.gemini.spModel.pio/src/main/resources/resources/SpXML2.dtd
<!--
  This DTD describes the second generation of the Gemini Observing Tool/Phase 1
  program export/import interchange format. No Namespace version

  $Id: SpXML2.dtd 4888 2004-08-02 22:56:25Z shane $

  Author: Kim Gillies, Gemini Observatory

  This file can contain a root level phase1 or phase2 document.

-->

<!--
The GEMINI_P1P2_DTD_VERSION is updated whenever the structure or data
types of the DTD are altered.
-->
<!ENTITY GEMINI_P1P2_DTD_VERSION "0.91">

<!--
The document is the root element containing all the information for the Phase1
or Phase II document. A document is any number of containers in any order.

The document is required to have a version attribute set to the value of the
DTD used for the document instance.  Processesors can take action based upon
the version of the document.

A P1/P2 document consists of a number of containers containing paramset
elements or other containers.

The containers are purely structure elements and are there to indicate
to the reader/writer what program items should be created.

The paramset elements contain the content of the database data objects.

The container element and the paramset element each have a set of
attributes as described below.
-->
<!ELEMENT document (container*)>
<!ATTLIST document
          version   CDATA #FIXED "&GEMINI_P1P2_DTD_VERSION;"
          xmlns     CDATA #FIXED "http://ftp.gemini.edu/dtds/p1p2"
>

<!--
The container elements indicate the structure of the program and provide
information as attributes that are used by the reader/writer
to interact with a database and to construct the program.  The containers
implement the composite pattern.

The container element can include one or more attributes that can help the
processor of the file.  They are described here:

kind - The container is required to have a kind.  The kind can be whatever
is required by the processing program.  For a Gemini program, the kind values
are things like: program, observation, phase1, obsComp and seqComp.

A container contains three attributes that are used to give the reader program
information about the database object that should be created.  The attributes
are type, subtype, and version.  The three attributes make a tuple that should
uniquely identify the configuration for the reader.

In the OT, the container is generally the configuration of a data object.
The type and subtype identify the data object which then uses the version
to handle the configuration in a version-specific way (if needed).  It's
possible for different versions of an observation to be handled differently.
The type, subtype, and version are used to create the correct object
which is then initialized by the contained paramset elements.  Note that a
container can contain paramset elements and other containers, but a paramset
element can only contain param elements or other paramset elements.

The container attributes related to construction and initialization are:

kind     - the kind is a hint to the reader suggesting the type of object
           held by the container.
type     - the paramset can have a type that indicates a broad category
           (like "instrument").
subtype  - the paramset can have a subtype that indicates a refinement
           within the broad category (like "niri").
version  - the version is a string that indicates the version of the
           type/subtype configuration. (like "2003B")

A fourth optional attribute is key.
key      - the key is a 128 byte string that uniquely identifies the database
           instance.

name	 - a name can optionally be provided to help the reader.  For instance, 
           with the observation, this includes the observation ID.

The kind and type attributes are required; the others are optional.

The container element has one more optional attribute called sequence.

sequence - containers sometimes must be ordered within a parent container.
           The sequence attribute is to be used to provide this ordering
           to readers.  Possible values are "0", "1", "2", ...  The lower
           values should be displayed first when shown in a list.

Note:  It is assumed that the reader/writer will make its attributes available
       to the created data object as needed.
-->
<!ENTITY % containerAttributes
       "kind     CDATA #REQUIRED
        type     CDATA #REQUIRED
        subtype  CDATA #IMPLIED
        name     CDATA #IMPLIED
        version  CDATA #REQUIRED
        sequence CDATA #IMPLIED
        key      CDATA #IMPLIED">

<!ELEMENT container (paramset | container)*>
<!ATTLIST container %containerAttributes;>


<!--
A paramset is an element that groups the state of a data object as param
elements and other paramset elements.  The relationship between
paramset and contained paramset and param elements is parent-child.

A paramset is some number of param elements or other paramsets in any order.

The paramset can include one or more attributes that can help the
processor of the file.

name - The paramset is required to have a name.  The name can be whatever
       is required by the processing program.  This attribute is the only
       required paramset attribute.  It is not required that the name be
       unique within the scope of its parent.

kind - The paramset can have a kind attribute that serves as a hint to the
       reader about what the paramset is.  For example, this is usually only
       set on the first parameset and is set to 'dataObj'.

The paramset can have one or more attributes to describe how the program
should present or handle the contained information.

editable - the paramset (and all its children) can be read-only if
           editable is set to false.  The default value is true.  By
           default all paramsets are editable.  This attribute is not
           required.
access   - a paramset (and all its children) can be public or private.  If
           the access is private, the reading program should not display
           the information to the user unless the program is permitted.
           Values can be public or private.  This attribute is used by the
           Gemini Science Archive to determine which parts of a Phase 2
           program can be exposed to GSA users.  By default, access is
           public and access should be assumed to be public unless
           explicitly set to private.  A writer is not required to attach
           an access attribute to every paramset.
sequence - paramsets sometimes must be ordered within a parent container.
           The sequence attribute is to be used to provide this ordering
           to readers.  Possible values are "0", "1", "2", ...  The lower
           values should be displayed first when shown in a list.

Paramsets have two attributes to allow them to be shared within a program.
This is just like the ID and IDREF attributes in the XML spec, but the
values are not checked by the parser.

id       - the paramset is marked with a string id value that can be
           referenced elsewhere in the program.
ref      - one paramset can refer the another "id" value.  The behavior
           is that the paramset should contain the same children as the
           referenced paramset.
-->
<!ENTITY % paramsetAttributes
        "name    CDATA #REQUIRED
        kind     CDATA #IMPLIED
        editable (true|false) 'true'
        access   (public|private) 'public'
        sequence CDATA #IMPLIED
        ref      CDATA #IMPLIED
        id       CDATA #IMPLIED">
<!ELEMENT paramset (paramset|param)*>
<!ATTLIST paramset %paramsetAttributes;>

<!--
A param element is a single thing with a name and value.

The param has a name.  Some param elements have no values.  A param can
be accompanied by a "units" attribute.


name     - a param is required to have a name that describes what the
           value is.  It is not required that param names be unique within
           the parent container.
value    - the value is one value for the named
           param. This attribute is optional.  Generally, it is preferred
           that the value be entered as a child.

           Multiple values should be represented as multiple value children
           elements.
units    - a param can have units that may be optionally included.  The
           units are strings that will be defined (TBD).

Optionally, the param can define its value as zero or more value children
elements.  For longer element values, this is convenient beacuse attributes
are more restrictive about their content.

A param should not have a value parameter and a value child at the same
time.  This is an error but is not checked for in the schema.
-->
<!ELEMENT param (value)*>
<!ATTLIST param
          name     CDATA #REQUIRED
          value    CDATA #IMPLIED
          units    CDATA #IMPLIED
>

<!--
A param element is a single thing with a name and value.

The value is one of the parameter values.  With arrays, there can be more
than one value and their order should be specified with a sequence attribute.

sequence - Values sometimes must be ordered within the param.  Possible values 
           are "0", "1", "2", ...  This is the proper way to specify an ordered 
           sequence of values of the same type.
-->
<!ELEMENT value (#PCDATA)>
<!ATTLIST value
          sequence  CDATA #IMPLIED
>

=== PabloMartinRavelo/ocs/bundle/edu.gemini.spModel.io/src/test/resources/edu/gemini/spModel/io/impl/migration/to2017A/vesta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document PUBLIC "-//Gemini Observatory//DTD for Storage of P1 and P2 Documents//EN" "http://ftp.gemini.edu/Support/xml/dtds/SpXML2.dtd">

<document>
  <container kind="program" type="Program" version="2016B-2" subtype="basic" key="298e2411-6551-4551-a17c-005c5e13a827" name="">
    <paramset name="Science Program" kind="dataObj">
      <param name="programMode" value="QUEUE"/>
      <param name="tooType" value="none"/>
      <param name="programStatus" value="PHASE2"/>
      <param name="nextObsId" value="1"/>
      <paramset name="timeAcct"/>
      <param name="awardedTime" value="0.0" units="hours"/>
      <param name="fetched" value="true"/>
      <param name="completed" value="false"/>
      <param name="notifyPi" value="YES"/>
    </paramset>
    <container kind="observation" type="Observation" version="2014A-1" subtype="basic" key="98635570-1426-41d5-bd8a-17136cf2e603" name="">
      <paramset name="Observation" kind="dataObj">
        <param name="title" value="GMOS-N Observation"/>
        <param name="libraryId" value=""/>
        <param name="priority" value="LOW"/>
        <param name="tooOverrideRapid" value="false"/>
        <param name="phase2Status" value="PI_TO_COMPLETE"/>
        <paramset name="schedulingBlock">
          <param name="start" value="1477935000000"/>
          <paramset name="duration">
            <param name="tag" value="unstated"/>
          </paramset>
        </paramset>
        <param name="qaState" value="UNDEFINED"/>
        <param name="overrideQaState" value="false"/>
      </paramset>
      <container kind="obsComp" type="Scheduling" version="2009A-1" subtype="conditions" key="eab019c6-0ef4-4b43-b20d-1a1a35bac53f" name="Observing Conditions">
        <paramset name="Observing Conditions" kind="dataObj">
          <param name="CloudCover" value="ANY"/>
          <param name="ImageQuality" value="ANY"/>
          <param name="SkyBackground" value="ANY"/>
          <param name="WaterVapor" value="ANY"/>
          <param name="ElevationConstraintType" value="NONE"/>
          <param name="ElevationConstraintMin" value="0.0"/>
          <param name="ElevationConstraintMax" value="0.0"/>
          <paramset name="timing-window-list"/>
        </paramset>
      </container>
      <container kind="obsComp" type="Telescope" version="2009B-1" subtype="targetEnv" key="dcd6271c-a0c2-4093-b98d-b2003824b159" name="Targets">
        <paramset name="Targets" kind="dataObj">
          <paramset name="targetEnv">
            <paramset name="base">
              <paramset name="target">
                <param name="name" value="Vesta"/>
                <paramset name="horizons-designation">
                  <param name="num" value="4"/>
                  <param name="tag" value="asteroid-old-style"/>
                </paramset>
                <paramset name="ephemeris">
                  <param name="site" value="GN"/>
                  <paramset name="ephemeris-element">
                    <param name="time" value="1467331200000"/>
                    <paramset name="coordinates">
                      <param name="ra" value="78.66414833333334"/>
                      <param name="dec" value="20.211091944444433"/>
                    </paramset>
                  </paramset>
                  <paramset name="ephemeris-element">
                    <param name="time" value="1477921200000"/>
                    <paramset name="coordinates">
                      <param name="ra" value="124.40285291666669"/>
                      <param name="dec" value="19.050720555555586"/>
                    </paramset>
                  </paramset>
                  <paramset name="ephemeris-element">
                    <param name="time" value="1488313080000"/>
                    <paramset name="coordinates">
                      <param name="ra" value="112.37534291666668"/>
                      <param name="dec" value="26.111878888888896"/>
                    </paramset>
                  </paramset>
                </paramset>
                <param name="tag" value="nonsidereal"/>
              </paramset>
            </paramset>
            <paramset name="guideEnv">
              <param name="primary" value="0"/>
              <paramset name="guideGroup">
                <param name="tag" value="AutoInitialTag"/>
              </paramset>
            </paramset>
          </paramset>
        </paramset>
      </container>
      <container kind="obsComp" type="Instrument" version="2009A-1" subtype="GMOS" key="9a0a060c-98ef-4cd9-bd2d-e98d95c34e1c" name="GMOS-N">
        <paramset name="GMOS-N" kind="dataObj">
          <param name="exposureTime" value="0.0"/>
          <param name="posAngle" value="0"/>
          <param name="coadds" value="1"/>
          <param name="adc" value="NONE"/>
          <param name="ampCount" value="SIX"/>
          <param name="gainChoice" value="LOW"/>
          <param name="ampReadMode" value="SLOW"/>
          <param name="detectorManufacturer" value="E2V"/>
          <param name="disperser" value="MIRROR"/>
          <param name="fpuMode" value="BUILTIN"/>
          <param name="fpu" value="FPU_NONE"/>
          <param name="filter" value="NONE"/>
          <param name="ccdXBinning" value="ONE"/>
          <param name="ccdYBinning" value="ONE"/>
          <param name="issPort" value="SIDE_LOOKING"/>
          <param name="posAngleConstraint" value="FIXED"/>
          <param name="stageMode" value="FOLLOW_XY"/>
          <param name="dtaXOffset" value="ZERO"/>
          <param name="builtinROI" value="FULL_FRAME"/>
          <param name="useNS" value="FALSE"/>
          <param name="mosPreimaging" value="NO"/>
        </paramset>
      </container>
      <container kind="obsQaLog" type="ObsLog" version="2009A-1" subtype="qa" key="3a54bce1-20a5-4a52-8094-79f7cd8259e5" name="Observing Log">
        <paramset name="Observing Log" kind="dataObj">
          <paramset name="obsQaRecord"/>
        </paramset>
      </container>
      <container kind="obsExecLog" type="ObsLog" version="2009A-1" subtype="exec" key="851e0860-9262-4353-af04-1bdebadd8f69" name="Observation Exec Log">
        <paramset name="Observation Exec Log" kind="dataObj">
          <paramset name="obsExecRecord">
            <paramset name="datasets"/>
            <paramset name="events"/>
            <paramset name="configMap"/>
          </paramset>
        </paramset>
      </container>
      <container kind="seqComp" type="Iterator" version="2012A-1" subtype="base" key="68965315-ddf0-4846-b703-6231cb34af78" name="Sequence">
        <paramset name="Sequence" kind="dataObj"/>
        <container kind="seqComp" type="Observer" version="2009A-1" subtype="observe" key="11aaa331-888c-4be0-950b-39c12a0a1f0f" name="Observe">
          <paramset name="Observe" kind="dataObj">
            <param name="repeatCount" value="1"/>
            <param name="class" value="SCIENCE"/>
          </paramset>
        </container>
      </container>
    </container>
  </container>
  <container kind="versions" type="versions" version="1.0">
    <paramset name="node">
      <param name="key" value="298e2411-6551-4551-a17c-005c5e13a827"/>
      <param name="ada5211d-fc1d-4f8a-ac32-ea9fdded85dc" value="1"/>
    </paramset>
    <paramset name="node">
      <param name="key" value="68965315-ddf0-4846-b703-6231cb34af78"/>
      <param name="ada5211d-fc1d-4f8a-ac32-ea9fdded85dc" value="2"/>
    </paramset>
    <paramset name="node">
      <param name="key" value="9a0a060c-98ef-4cd9-bd2d-e98d95c34e1c"/>
      <param name="ada5211d-fc1d-4f8a-ac32-ea9fdded85dc" value="2"/>
    </paramset>
    <paramset name="node">
      <param name="key" value="11aaa331-888c-4be0-950b-39c12a0a1f0f"/>
      <param name="ada5211d-fc1d-4f8a-ac32-ea9fdded85dc" value="1"/>
    </paramset>
    <paramset name="node">
      <param name="key" value="851e0860-9262-4353-af04-1bdebadd8f69"/>
      <param name="ada5211d-fc1d-4f8a-ac32-ea9fdded85dc" value="1"/>
    </paramset>
    <paramset name="node">
      <param name="key" value="dcd6271c-a0c2-4093-b98d-b2003824b159"/>
      <param name="ada5211d-fc1d-4f8a-ac32-ea9fdded85dc" value="10"/>
    </paramset>
    <paramset name="node">
      <param name="key" value="3a54bce1-20a5-4a52-8094-79f7cd8259e5"/>
      <param name="ada5211d-fc1d-4f8a-ac32-ea9fdded85dc" value="1"/>
    </paramset>
    <paramset name="node">
      <param name="key" value="98635570-1426-41d5-bd8a-17136cf2e603"/>
      <param name="ada5211d-fc1d-4f8a-ac32-ea9fdded85dc" value="1"/>
    </paramset>
    <paramset name="node">
      <param name="key" value="eab019c6-0ef4-4b43-b20d-1a1a35bac53f"/>
      <param name="ada5211d-fc1d-4f8a-ac32-ea9fdded85dc" value="1"/>
    </paramset>
  </container>
</document>
