=== PabloMartinRavelo/ocs/bundle/jsky.app.ot/src/main/resources/resources/DataProc.dtd
<!--
  This DTD describes the content of the DataProc.xml file, which 
  describes data processing recipes for the Gemini Observing Tool (OT).

  $Id: DataProc.dtd 4336 2004-01-20 07:57:42Z gillies $
-->

<!-- The DATAPROC_DTD_VERSION is updated whenever the structure or content
     of the DTD is altered.
-->
<!ENTITY DATAPROC_DTD_VERSION "0.1">


<!-- recipes is the top level element containing a list of recipe elements.
     The root element is required to have a version attribute set to
     the version of the DTD used in the document.
-->
<!ELEMENT recipes (recipe)+>
<!ATTLIST recipes
          version   CDATA #FIXED "&DATAPROC_DTD_VERSION;"
>


<!-- A recipe element describes a data processing operation or recipe
     and may contain inputs, outputs, and params items.
     Attributes:
     name              name used for UI display
     task              the name of the (IRAF) task to execute
     id                short name or id of the recipe
     desc              a short description of the recipe
-->
<!ELEMENT recipe (inputs*, outputs*, params*)>
<!ATTLIST recipe
          name             CDATA #REQUIRED
          task             CDATA #REQUIRED
          id               CDATA #REQUIRED
          desc             CDATA #REQUIRED
>


<!-- An inputs element may contain one or more input elements describing the recipe's input
     sources.
-->
<!ELEMENT inputs (input+)>

<!-- An input element describes one recipe input source.
     Attributes:
     name              name used for UI display
     desc              a short description of the input source
-->
<!ELEMENT input EMPTY>
<!ATTLIST input
          name             CDATA #IMPLIED
          desc             CDATA #IMPLIED
>



<!-- An outputs element may contain one or more output elements describing the recipe's outputs.
-->
<!ELEMENT outputs (output*)>

<!-- An output element describes one recipe output.
     Attributes:
     name              name used for UI display
     desc              a short description of the output
-->
<!ELEMENT output EMPTY>
<!ATTLIST output
          name             CDATA #IMPLIED
          desc             CDATA #IMPLIED
>



<!-- An params element may contain one or more param elements describing the recipe's parameters.
-->
<!ELEMENT params (param+)>

<!-- An param element describes one recipe parameter.
     Attributes:
     type              the type of the parameter: one of: "string", "decimal", "integer", "choice",
                       or "boolean", where "choice" means one of the items described in the "choice" 
                       element. "boolean" is interpreted as a choice of "yes" and "no".

     name              name used for UI display
     value	       the default value
     desc              a short description of the parameter
     level	       the OLDP parameter level (1, 2, or 3)
                       1:  OLDP must set this parameter, it is required for execution
                       2:  Default value from the script is usually ok and should be
                           visible to the OLDP user, but the user might need to reconfigure the value
                       3:  Should normally be hidden from the OLDP user, "expert" 
-->
<!ELEMENT param (choice*)>
<!ATTLIST param
          type             (String|double|int|boolean|choice) "String"
          name             CDATA #REQUIRED
          value            CDATA #IMPLIED
          desc             CDATA #REQUIRED
          level            (1|2|3) "1"
>


<!-- An choice element describes one choice for a recipe parameter. This element should
     only be used with parameters of type "choice".
     Attributes:
     name              name used for UI display
     desc              a short description of the choice
-->
<!ELEMENT choice EMPTY>
<!ATTLIST choice
          name             CDATA #REQUIRED
          desc             CDATA #IMPLIED
>

=== PabloMartinRavelo/ocs/bundle/jsky.app.ot/src/main/resources/resources/conf/DataProc.xml
<?xml version="1.0"?>
<!DOCTYPE recipes PUBLIC "-//Gemini Observatory//DTD for Data Processing//EN" "DataProc.dtd">
<!--
  This document describes data processing recipes for the
  Gemini Observing Tool (OT). An element is defined for each recipe
  and corresponds to the DataProcRecipeNode class.
-->

<recipes version="0.1">

<!-- gemseeing -->
<!--
    <recipe name="gemseeing" task="gemini.gemtools.gemseeing" id="gemseeing"
            desc="Semi-automatic method for determination of image quality for seeing data.">
        <inputs>
            <input name="image"  desc="Image (w/ MEF extension)"/>
        </inputs>
        <outputs>
            <output name="coords" desc="daofind output file"/>
            <output name="psffile" desc="File for psfmeasure output"/>
        </outputs>
        <params>
            <param type="boolean"  name="fl_inter"     value="no"       desc="Interactive use"				       level="3"/>
            <param type="boolean"  name="fl_useall"    value="no"       desc="Use all objects if N>maxnobj"		       level="3"/>
            <param type="int"      name="maxnobj"      value="100"      desc="Approximate maximum number of objects"           level="3"/>
            <param type="boolean"  name="fl_update"    value="yes"      desc="Update image keywords"			       level="3"/>
            <param type="boolean"  name="fl_keep"      value="yes"      desc="Keep output tables"			       level="3"/>
            <param type="boolean"  name="fl_strehl"    value="yes"      desc="Derive Strehl ratio if defined for instrument"   level="3"/>
            <param type="boolean"  name="fl_overwrite" value="no"       desc="Overwrite results from previous use"	       level="2"/>
            <param type="boolean"  name="fl_cleed"     value="yes"      desc="Clean measurements of EED of outliers"	       level="3"/>
            <param type="String"   name="key_inst"     value="INSTRUME" desc="Keyword for instrument"		               level="3"/>
            <param type="String"   name="key_camera"   value="CAMERA"   desc="Keyword for NIRI camera"		               level="3"/>
            <param type="String"   name="key_ron"      value="RDNOISE"  desc="Keyword for read out noise in electrons"         level="3"/>
            <param type="String"   name="key_gain"     value="GAIN"     desc="Keyword for gain in electrons/ADU"	       level="3"/>
            <param type="String"   name="key_filter"   value="FILTER"   desc="Keyword for filter"			       level="3"/>
            <param type="String"   name="instrument"   value=""         desc="Instrument"				       level="3"/>
            <param type="String"   name="camera"       value=""         desc="NIRI camera"				       level="3"/>
            <param type="double"   name="ron"          value="1."       desc="Read out noise in electrons"	               level="3"/>
            <param type="double"   name="gain"         value="1."       desc="Gain in e-/ADU"		                       level="3"/>
            <param type="String"   name="filter"       value=""         desc="Filter name"				       level="3"/>
            <param type="boolean"  name="fl_database"  value="yes"      desc="Use database values for parameters"	       level="3"/>
            <param type="String"   name="database"     value="gemtools$gemseeing.dat"        desc="Database to use"	       level="2"/>
            <param type="String"   name="stdatabase"   value="gemtools$gemseeing_strehl.dat" desc="Database for Strehl ratio"  level="3"/>
            <param type="double"   name="pixscale"     value="0.5"      desc="Pixel scale arcsec/pixel [database]"             level="2"/>
            <param type="double"   name="fwhmin"       value="1."       desc="Input FWHM PSF in arcsec (daofind) [database]"   level="1"/>
            <param type="double"   name="datamax"      value="40000."   desc="Maximum valid data value [database]"             level="2"/>
            <param type="double"   name="radius"       value="0."       desc="Radius in pixels for fit [database]"             level="3"/>
            <param type="double"   name="buffer"       value="8."       desc="Buffer zone in pixels for sky [database]"        level="3"/>
            <param type="double"   name="width"        value="2."       desc="Width in pixels for sky [database]"	       level="3"/>
            <param type="double"   name="fwhmnonao"    value="0.5"      desc="App non-AO FWHM in arcsec if using AO"           level="3"/>
            <param type="double"   name="sigthres"     value="10."      desc="Threshold in sigma of sky (daofind)"             level="2"/>
            <param type="double"   name="threshold"    value="INDEF"    desc="Threshold for daofind (daofind)"	               level="2"/>
            <param type="int"      name="niter"        value="3"        desc="Number of iterations (psfmeasure)"	       level="3"/>
            <param type="double"   name="mdaofaint"    value="-2.0"     desc="Faintest magnitude from daofind"                 level="3"/>
            <param type="double"   name="fwhmmin"      value="0."       desc="Minimim fwhm in arcsec"		               level="3"/>
            <param type="double"   name="fwhmmax"      value="0."       desc="Maximum fwhm in arcsec"		               level="3"/>
            <param type="double"   name="sharplow"     value="0.3"      desc="Minimum sharp from daofind"		       level="3"/>
            <param type="double"   name="sharphigh"    value="1.0"      desc="Maximum sharp from daofind"		       level="3"/>
            <param type="double"   name="sharpsig"     value="3."       desc="Sigma selection on sharp from daofind"           level="3"/>
            <param type="double"   name="dmagsig"      value="2."       desc="Sigma selection on magnitude difference"         level="3"/>
            <param type="double"   name="fwhmsig"      value="2.5"      desc="Sigma selection on FWHM"		               level="3"/>
            <param type="boolean"  name="verbose"      value="yes"      desc="Print intermediate results"		       level="2"/>
        </params>
    </recipe>
-->

<!-- imcoadd -->
    <recipe name="imcoadd" task="gemini.gemtools.imcoadd" id="imcoadd"
            desc="Combine science images, includes cleaning for cosmic ray events.">
        <inputs>
            <input name="images" desc="Input NIRI image(s)"/>
            <input name="badpixfile" desc="Bad pixel file or image"/>
        </inputs>
        <outputs>
	    <output name="outimage" desc="Output image name if not derived from reference"/>
        </outputs>
        <params>
            <param type="String" name="sci_ext" value="SCI" desc="Science extension name if MEF input"          level="3"/>
            <param type="String" name="var_ext" value="VAR" desc="Variance extension name if MEF input"         level="3"/>
            <param type="String" name="dq_ext" value="DQ" desc="Data quality extension name if MEF input"       level="3"/>
            <param type="String" name="immasks" value="DQ" desc="Masks of bad pixels for each image"           level="3"/>
            <param type="String" name="database" value="imcoadd.dat" desc="Database file for transformations"   level="3"/>
            <param type="double" name="threshold" value="20." desc="Threshold for daofind, sigma above sky"       level="2"/>
            <param type="double" name="fwhm" value="7." desc="FWHMPSF for daofind, in pixels (ref)"         level="2"/>
            <param type="double" name="box" value="20." desc="Box size for centering (ref)"                 level="2"/>
            <param type="choice" name="alignmethod" value="wcs" desc="Method for rough alignment of images (wcs|user|twodx|header)" level="2">
	        <choice	name="wcs"/>
		<choice name="user"/>
		<choice name="twodx"/>
		<choice name="header"/>
            </param>
            <param type="String" name="asection" value="default" desc="Image sections (2) (alignmethod=twodx)"   level="3"/>
            <param type="int"  name="xwindow" value="181" desc="Window size to search if using twodx"    level="3"/>
            <param type="String" name="key_inst" value="INSTRUME" desc="Header keyword for instrument"          level="3"/>
            <param type="String" name="key_camera" value="CAMERA" desc="Header keyword for camera (NIRI only)"  level="3"/>
            <param type="String" name="key_inport" value="INPORT" desc="Header keyword for ISS port"            level="3"/>
            <param type="String" name="key_xoff" value="default" desc="Header keyword for instrument X-offset (alignmethod=header)"  level="3"/>
            <param type="String" name="key_yoff" value="default" desc="Header keyword for instrument Y-offset (alignmethod=header)"  level="3"/>
            <param type="double" name="instscale" value="1." desc="Scale for offsets arcsec/unit (alignmethod=header)"          level="3"/>
            <param type="choice" name="xsign" value="default" desc="XOFFSET sign relative to detector (alignmethod=header)" level="3">
	        <choice	name="default"/>
		<choice name="negative"/>
		<choice name="positive"/>
            </param>
            <param type="choice" name="ysign" value="default" desc="YOFFSET sign relative to detector (alignmethod=header)" level="3">
	        <choice	name="default"/>
		<choice name="negative"/>
		<choice name="positive"/>
            </param>
            <param type="String" name="key_pixscale" value="PIXSCALE" desc="Header keyword for pixel scale in arcsec/pixel" level="3"/>
            <param type="double" name="pixscale" value="1." desc="Pixel scale arcsec/pixel"          level="3"/>
            <param type="double" name="dispmag" value="1.0" desc="Magnify for display"                            level="3"/>
            <param type="boolean" name="rotate" value="no" desc="Assume rotation > 0.5 deg"                        level="3"/>
